### ISSUE TITLE
Budget Approval

### ISSUE THREAD

**Issue by LambdaLawliet** [ConfederationC/2016_Project#8]
For the following commit to city plan branch

BUDGET LIST
*Power Communication: $
*Industry: $
*Recreation: $
*Propaganda: $
*Transport: $

**Comment by F1xx** [comment]
Indusrty has added their required budget, currently estimating $1.3 billion.

**Comment by DavidAskwith** [comment]
Recreations budget is 12 trillion dollars. Its worth ever penny!

**Comment by bwillson1** [comment]
Shouldn't there be a budget for the city's refuse/water management system? We propose $20 billion for the initial investment with an operating cost of about $1.8 million per year

**Comment by bwillson1** [comment]
thanks fam 💯 💯 💯 

city plan is mad 🔥 🔥 🔥

**Comment by LambdaLawliet** [comment]
IMPORTANT MESSAGE!!. Submissions for budget will be closed today 5:00 PM. If you did not commit on @ConfederationC/cityplan/BudgetDecision, City Plan will provide you with a default budget of 800 million

**Comment by stomas96** [comment]
Transportation budget is 15 billion dollars.

Thanks
